Propagate fatal errors during macro expansion.
Fixes #10552. Previously, fatal errors got swallowed during macro
expansion.  In the case of implicit blackbox macros, a fatal error (for
example OutOfMemoryException) got reported with the message "exception
during macro expansion". For implicit whitebox macros the fatal error is
not even reported unless -Xlog-implicits is enabled. By default, the
user only sees a cryptic "implicit not found" error message.  See #10649.

This commit changes the error handling of exceptions during macro
expansion to propagate fatal errors. Now fatal errors are left uncaught
and crash compilation with a full stack trace instead of getting
swallowed.

```
error: java.lang.OutOfMemoryError
    at Macros$BlackBox$.materializeImpl(so.scala:8)
```